# Unique project identifier in SonarQube
sonar.projectKey=sonarqube-devsecops-lab

# Display name in SonarQube UI
sonar.projectName=sonarqube-devsecops-lab

# Project version
sonar.projectVersion=1.0

# Source code location
sonar.sources=.

# Source encoding
sonar.sourceEncoding=UTF-8

# SonarQube Server URL
sonar.host.url=http://localhost:9000
